name: Foundry CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly  # or use 'stable'

      - name: Install dependencies
        run: forge install

      - name: Format check
        run: forge fmt --check

      - name: Build contracts
        run: forge build

      - name: Run tests
        run: forge test
